name: Publish to Test PyPI
run-name: publish-testpypi
on:
  push:
    branches:
      - dev

jobs:
  Publish-to-testPyPI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install poetry
        run: |
          python -m pip install poetry==1.3.2

      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true
          python -m poetry config repositories.test-pypi https://test.pypi.org/legacy/
          python -m poetry config pypi-token.test-pypi ${{secrets.TEST_PYPI}}

      - name: Cache the virtualenv
        uses: actions/cache@v3.2.3
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          python -m poetry install

      - name: Build and publish with Poetry
        run: |
          python -m poetry build
          python -m poetry version prerelease
          python -m poetry publish -r test-pypi
